In [1]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_excel('rvb_rvc_remittance_9_jun_15_jun_2025.xlsx', sheet_name='Sheet1')
df.head()

,REPORT_DATE,APPROVAL_DATETIME,NR_NUMBER,TXN_ID,CHANNEL,MERCHANT_PAR,MERCHANT_WALLET_ENC,MERCHANT_WALLET,MERCHANT_NAME,CUSTOMER_PAR,...,TXN_AMT,FEE_AMT,COMM_AMT,TXN_STATUS,ACCOUNT_ID1,RECHARGE_ID,UPDATE_DATETIME,TXN_TRUST_LEVEL,TXN_CUSTOMER_SEGMENT,PAYMENT_METHOD
0,6/9/2025,09-JUN-25 12.00.03.330000 AM,CS0000000071093539,740PI1TK,THIRD PARTY,Q14DB3B89F2593E5120445E40F0,98883FF10BED59545380B339D3ABD9AE,1730006634,IFIC Bank Ltd.,Q14AAC178E441AAD91475EFE1E0,...,600.0,NaN,NaN,APPROVED,A,687300066345399.20250608235502.740PI1TK.174940...,NaN,4,1,KONADFS
1,6/9/2025,09-JUN-25 12.00.04.759000 AM,CS0000000071093390,740PI1VV,THIRD PARTY,Q1C7B8A38A139205E0FEA9158E6,5BEFD0E4A2D688482B269DF78E63F443,1844480589,VISA,Q1EDA6F88310610B334C66DAD01,...,2600.0,NaN,NaN,APPROVED,M01944690301,MjAyNTA2MDguQ1MwMDAwMDAwMDcxMDkzMzkw,NaN,4,1,VISA-EASTERN BANK LIMITED/VISA
2,6/9/2025,09-JUN-25 12.00.06.881000 AM,CS0000000071093476,740PI1Y9,THIRD PARTY,Q110AEB21238B66FA9E844CB040,D25D0586E4894933C5C419EF4B1B0357,1309015693,Trust Bank Limited,Q1B69B611FFD9807CC6916AE1EE,...,1000.0,NaN,NaN,APPROVED,A0029-0214072142,683090156935399.20250608235427.740PI1Y9.174940...,NaN,4,1,KONADFS
3,6/9/2025,09-JUN-25 12.00.08.303000 AM,CS0000000071093540,740PI22F,THIRD PARTY,Q110AEB21238B66FA9E844CB040,D25D0586E4894933C5C419EF4B1B0357,1309015693,Trust Bank Limited,Q164A047FBFF9B0FDBB4BE25AF0,...,5000.0,NaN,NaN,APPROVED,A4002-0310002547,683090156935399.20250608235427.740PI22F.174940...,NaN,4,3,KONADFS
4,6/9/2025,09-JUN-25 12.00.08.827000 AM,CS0000000071093449,740PI25C,THIRD PARTY,Q14DB3B89F2593E5120445E40F0,98883FF10BED59545380B339D3ABD9AE,1730006634,IFIC Bank Ltd.,Q11FA1FFB1F5B0598C816177A3A,...,10200.0,NaN,NaN,APPROVED,A,687300066345399.20250608235508.740PI25C.174940...,NaN,4,1,KONADFS

In [6]:
df.head(10)

,REPORT_DATE,APPROVAL_DATETIME,NR_NUMBER,TXN_ID,CHANNEL,MERCHANT_PAR,MERCHANT_WALLET_ENC,MERCHANT_WALLET,MERCHANT_NAME,CUSTOMER_PAR,...,TXN_AMT,FEE_AMT,COMM_AMT,TXN_STATUS,ACCOUNT_ID1,RECHARGE_ID,UPDATE_DATETIME,TXN_TRUST_LEVEL,TXN_CUSTOMER_SEGMENT,PAYMENT_METHOD
0,6/9/2025,09-JUN-25 12.00.03.330000 AM,CS0000000071093539,740PI1TK,THIRD PARTY,Q14DB3B89F2593E5120445E40F0,98883FF10BED59545380B339D3ABD9AE,1730006634,IFIC Bank Ltd.,Q14AAC178E441AAD91475EFE1E0,...,600.0,NaN,NaN,APPROVED,A,687300066345399.20250608235502.740PI1TK.174940...,NaN,4,1,KONADFS
1,6/9/2025,09-JUN-25 12.00.04.759000 AM,CS0000000071093390,740PI1VV,THIRD PARTY,Q1C7B8A38A139205E0FEA9158E6,5BEFD0E4A2D688482B269DF78E63F443,1844480589,VISA,Q1EDA6F88310610B334C66DAD01,...,2600.0,NaN,NaN,APPROVED,M01944690301,MjAyNTA2MDguQ1MwMDAwMDAwMDcxMDkzMzkw,NaN,4,1,VISA-EASTERN BANK LIMITED/VISA
2,6/9/2025,09-JUN-25 12.00.06.881000 AM,CS0000000071093476,740PI1Y9,THIRD PARTY,Q110AEB21238B66FA9E844CB040,D25D0586E4894933C5C419EF4B1B0357,1309015693,Trust Bank Limited,Q1B69B611FFD9807CC6916AE1EE,...,1000.0,NaN,NaN,APPROVED,A0029-0214072142,683090156935399.20250608235427.740PI1Y9.174940...,NaN,4,1,KONADFS
3,6/9/2025,09-JUN-25 12.00.08.303000 AM,CS0000000071093540,740PI22F,THIRD PARTY,Q110AEB21238B66FA9E844CB040,D25D0586E4894933C5C419EF4B1B0357,1309015693,Trust Bank Limited,Q164A047FBFF9B0FDBB4BE25AF0,...,5000.0,NaN,NaN,APPROVED,A4002-0310002547,683090156935399.20250608235427.740PI22F.174940...,NaN,4,3,KONADFS
4,6/9/2025,09-JUN-25 12.00.08.827000 AM,CS0000000071093449,740PI25C,THIRD PARTY,Q14DB3B89F2593E5120445E40F0,98883FF10BED59545380B339D3ABD9AE,1730006634,IFIC Bank Ltd.,Q11FA1FFB1F5B0598C816177A3A,...,10200.0,NaN,NaN,APPROVED,A,687300066345399.20250608235508.740PI25C.174940...,NaN,4,1,KONADFS
5,6/9/2025,09-JUN-25 12.00.11.841000 AM,CS0000000071093488,740PI2CG,THIRD PARTY,Q1C7B8A38A139205E0FEA9158E6,5BEFD0E4A2D688482B269DF78E63F443,1844480589,VISA,Q1FE88B4A611A6B81F022843C90,...,1000.0,NaN,NaN,APPROVED,M01732625732,MjAyNTA2MDguQ1MwMDAwMDAwMDcxMDkzNDg4,NaN,4,1,VISA-EASTERN BANK LIMITED/VISA
6,6/9/2025,09-JUN-25 12.00.12.450000 AM,CS0000000071093527,740PI2CF,THIRD PARTY,Q15AB2CA3A4567E49457975EE30,9A0323777B32E8C8D328D5A2937578D3,1730332600,Agrani Bank Limited,Q14984D0C83D5F4F03022C7D689,...,1000.0,NaN,NaN,APPROVED,A0200*****6227,687303326005399.20250608235615.740PI2CF.174940...,NaN,4,1,KONADFS
7,6/9/2025,09-JUN-25 12.00.18.235000 AM,CS0000000071093450,740PI2OE,THIRD PARTY,Q1089EEB0D41DF07DB2E1B223E9,CC36CE2CE4FD377E5A46C30E74FFE2A8,1324412904,IBBL,Q1C080CC6E114E8D1770623CCAD,...,1000.0,NaN,NaN,APPROVED,A20507770201158529,683244129045399.20250609000017.740PI2OE.174940...,NaN,4,3,KONADFS
8,6/9/2025,09-JUN-25 12.00.18.378000 AM,CS0000000071093557,740PI2OF,THIRD PARTY,Q1A7B9FB7B19BE824297021E925,89AEC240457D8BDC4B27DAECE07262F8,1755556366,Shahjalal Islami Bank,Q1839B40874F917339FC6A5C4A6,...,500.0,NaN,NaN,APPROVED,A401312600001159,687555563665399.20250608235017.740PI2OF.174940...,NaN,4,1,KONADFS
9,6/9/2025,09-JUN-25 12.00.19.217000 AM,CS0000000071093396,740PI2R9,THIRD PARTY,Q1C7B8A38A139205E0FEA9158E6,5BEFD0E4A2D688482B269DF78E63F443,1844480589,VISA,Q19ABD1DC2105E7AC3072519F24,...,100.0,NaN,NaN,APPROVED,M01931446318,MjAyNTA2MDguQ1MwMDAwMDAwMDcxMDkzMzk2,NaN,4,1,VISA-EASTERN BANK LIMITED/VISA

In [8]:
df = df[['APPROVAL_DATETIME', 'CHANNEL', 'MERCHANT_NAME', 'TXN_AMT', 'FEE_AMT', 'COMM_AMT', 'TXN_STATUS', 'TXN_TRUST_LEVEL', 'TXN_CUSTOMER_SEGMENT', 'PAYMENT_METHOD']]

In [9]:
df.head()

,APPROVAL_DATETIME,CHANNEL,MERCHANT_NAME,TXN_AMT,FEE_AMT,COMM_AMT,TXN_STATUS,TXN_TRUST_LEVEL,TXN_CUSTOMER_SEGMENT,PAYMENT_METHOD
0,09-JUN-25 12.00.03.330000 AM,THIRD PARTY,IFIC Bank Ltd.,600.0,NaN,NaN,APPROVED,4,1,KONADFS
1,09-JUN-25 12.00.04.759000 AM,THIRD PARTY,VISA,2600.0,NaN,NaN,APPROVED,4,1,VISA-EASTERN BANK LIMITED/VISA
2,09-JUN-25 12.00.06.881000 AM,THIRD PARTY,Trust Bank Limited,1000.0,NaN,NaN,APPROVED,4,1,KONADFS
3,09-JUN-25 12.00.08.303000 AM,THIRD PARTY,Trust Bank Limited,5000.0,NaN,NaN,APPROVED,4,3,KONADFS
4,09-JUN-25 12.00.08.827000 AM,THIRD PARTY,IFIC Bank Ltd.,10200.0,NaN,NaN,APPROVED,4,1,KONADFS